# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 43ed5c79eff614c29b40601f3a4005218b9a5b3d1791a09a5c15dae6a3ea3ea68f7c786d538258a6f3d74149b9250152546df5460abc4c80a1b1727cb4da3ddd

test:
  secret_key_base: 78393ca803f2b2bb792f96aed9ad4fb3dbd76cb1f2796220fc48c6a9ce576e80dcf5fc6e0af9ebc3831a470e30ae652ef0e61206d24b0adc8447b65c9e048332

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
